name: Auto-assign Copilot Issues

on:
  issues:
    types: [labeled]

jobs:
  assign-to-copilot:
    if: github.event.label.name == 'copilot'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Assign issue to Copilot
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Try to assign the issue to copilot user, but continue if it fails
            try {
              await github.rest.issues.addAssignees({
                owner: owner,
                repo: repo,
                issue_number: issue_number,
                assignees: ['Copilot']
              });
              console.log('Successfully assigned issue to copilot user');
            } catch (error) {
              console.log(`Failed to assign issue: ${error.message}`);
              // Continue with the workflow
            }
            
            // Add a comment confirming the assignment
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              body: `🤖 This issue has been labeled for GitHub Copilot implementation.
              
              Copilot will follow the established patterns and guidelines in:
              - \`.github/copilot-instructions.md\`
              - \`docs/label-strategy.md\`
              
              Quality checks will be run before submitting a PR.`
            });