name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write  # For PyPI trusted publishing

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          
  # Build and publish package when a release is created
  build-and-publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mvn-mcp-server
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        
      - name: Create virtual environment
        run: uv venv
        
      - name: Build package
        run: |
          uv pip install build
          uv run python -m build
          
      - name: Validate built distributions
        run: |
          echo "Built packages:"
          ls -la dist/
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-packages-${{ needs.release-please.outputs.tag_name }}
          path: dist/
          retention-days: 90

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
          print-hash: true